version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: YamlDotNet
    versions:
    - 10.0.0
    - 11.0.1
    - 11.1.0
    - 9.1.4
  - dependency-name: EPPlus
    versions:
    - 5.5.2
    - 5.5.3
    - 5.5.4
    - 5.5.5
    - 5.6.0
    - 5.6.1
    - 5.6.2
  - dependency-name: DocumentFormat.OpenXml
    versions:
    - 2.12.1
    - 2.12.2
