version: "{build}"
branches:
  except:
    - gh-pages
platform:
  - Any CPU
configuration:
  - Release
before_build:
  - nuget restore
build:
  project: seedtable.sln
artifacts:
  - path: seedtable-gui/bin/Release
    name: seedtable
